title: Notes for Propulsion
author: Bryan Weber
# logo: logo.png

exclude_patterns: [homework]

# execute:
#   execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/bryanwweber/propulsion-notes
  branch: main

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  extra_footer: |
    <p xmlns:dct="http://purl.org/dc/terms/" xmlns:cc="http://creativecommons.org/ns#" class="license-text"><a rel="cc:attributionURL" property="dct:title" href="https://bryanwweber.github.io/propulsion-notes">Notes for Propulsion</a> by <span property="cc:attributionName">Bryan Weber</span> is licensed under <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" /><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" /><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" /></a></p>

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    html_show_copyright: false
    mathjax_config:
      TeX:
        Macros:
          vector: ["\\vec{#1}", 1]
          uvec: ["\\hat{#1}", 1]
          mag: ["\\lVert#1\\rVert", 1]
          cross: "\\times"
          unit: ["#1~\\mathrm{#2}", 2]
          pf: ["\\overline{#1}", 1]  # This is for the perifocal frame
          mat: ["\\left[\\mathbf{#1}\\right]", 1]
          Isp: "I_{\\text{sp}}"
    # MathJax 3 + Sphinx cannot currently use custom macros as defined here
    # See: https://github.com/executablebooks/jupyter-book/issues/963
    # and: https://github.com/executablebooks/jupyter-book/issues/917
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
